name: home_pause
description: "Aplicativo para auxiliar a praticar ginástica laboral no home office"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^5.0.0
  font_awesome_flutter: ^10.0.0
  cupertino_icons: ^1.0.6

  # Network
  http: ^1.1.0

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5

  # Storage
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # Code quality tools
  import_sorter: ^4.6.0

flutter:
  assets:
    - assets/
  uses-material-design: true

# Configuração do import_sorter para organizar imports
import_sorter:
  comments: false
  ignored_files:
    - \/lib\/.*\.g\.dart$
